

  // Premium, High-Contrast Light Mode UI Color Configuration
  const bg = dark ? "#0d0d0d" : "#fdfbfc";
  const surface = dark ? "#161616" : "#ffffff";
  const card = dark ? "#1c1c1c" : "#f7f9fa";
  const border = dark ? "#2a2a2a" : "#e2e8f0";
  const text = dark ? "#f0ede8" : "#0f172a";
  const muted = dark ? "#888888" : "#64748b";
  const accent = "#c8922a"; // signature industrial warm gold
  const accentLight = dark ? "#3a2700" : "#fef3c7";

 export const s = {
    root: {
      background: bg,
      color: text,
      fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      minHeight: "100vh",
      transition: "background 0.5s cubic-bezier(0.4, 0, 0.2, 1), color 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
      overflowX: "hidden",
    },
    nav: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      zIndex: 100,
      background: scrolled ? (dark ? "rgba(13,13,13,0.85)" : "rgba(253,251,252,0.85)") : "transparent",
      backdropFilter: scrolled ? "blur(16px)" : "none",
      borderBottom: scrolled ? `1px solid ${border}` : "none",
      transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
      padding: "0 clamp(1.5rem, 5vw, 4rem)",
    },
    navInner: {
      maxWidth: 1280,
      margin: "0 auto",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      height: scrolled ? 68 : 88,
      transition: "height 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    logo: {
      display: "flex",
      flexDirection: "column",
      lineHeight: 1,
    },
    logoMain: {
      fontSize: 22,
      fontWeight: 800,
      letterSpacing: "-0.03em",
      color: text,
    },
    logoSub: {
      fontSize: 10,
      letterSpacing: "0.18em",
      color: accent,
      textTransform: "uppercase",
      marginTop: 2,
    },
    navLinks: {
      display: isMobile ? "none" : "flex",
      gap: "2.5rem",
      listStyle: "none",
      margin: 0,
      padding: 0,
    },
    navLink: {
      fontSize: 13,
      letterSpacing: "0.06em",
      color: muted,
      cursor: "pointer",
      textTransform: "uppercase",
      fontWeight: 500,
      transition: "color 0.2s ease, transform 0.2s ease",
    },
    navRight: {
      display: "flex",
      alignItems: "center",
      gap: "1rem",
    },
    themeBtn: {
      background: "none",
      border: `1px solid ${border}`,
      borderRadius: 8,
      padding: "8px 14px",
      cursor: "pointer",
      color: text,
      fontSize: 13,
      fontWeight: 500,
      transition: "all 0.2s ease",
    },
    ctaBtn: {
      background: accent,
      color: "#fff",
      border: "none",
      borderRadius: 8,
      padding: "10px 22px",
      fontSize: 13,
      fontWeight: 600,
      letterSpacing: "0.05em",
      cursor: "pointer",
      textTransform: "uppercase",
      transition: "transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.2s ease",
    },
    hamburger: {
      display: isMobile ? "block" : "none",
      background: "none",
      border: "none",
      cursor: "pointer",
      color: text,
      fontSize: 24,
      padding: 4,
    },
    hero: {
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      padding: "120px clamp(1.5rem, 5vw, 4rem) 5rem",
      position: "relative",
      overflow: "hidden",
    },
    heroBg: {
      position: "absolute",
      inset: 0,
      background: dark
        ? "linear-gradient(160deg, #0d0d0d 0%, #1c150c 60%, #0d0d0d 100%)"
        : "linear-gradient(160deg, #fdfbfc 0%, #f7f1e5 60%, #fdfbfc 100%)",
      transition: "background 0.5s ease",
      zIndex: 0,
    },
    heroGrid: {
      position: "absolute",
      inset: 0,
      backgroundImage: `linear-gradient(${border} 1px, transparent 1px), linear-gradient(90deg, ${border} 1px, transparent 1px)`,
      backgroundSize: "80px 80px",
      opacity: dark ? 0.2 : 0.4,
      zIndex: 1,
    },
    heroAccentBar: {
      position: "absolute",
      top: "25%",
      right: "clamp(2rem, 10vw, 12rem)",
      width: 2,
      height: "45%",
      background: `linear-gradient(transparent, ${accent}, transparent)`,
      zIndex: 1,
      display: isMobile ? "none" : "block",
    },
    heroContent: { position: "relative", maxWidth: 1280, margin: "0 auto", width: "100%", zIndex: 2 },
    heroEyebrow: {
      fontSize: 12,
      letterSpacing: "0.22em",
      color: accent,
      textTransform: "uppercase",
      marginBottom: "1.5rem",
      fontWeight: 600,
    },
    heroH1: {
      fontSize: "clamp(2.5rem, 7vw, 6rem)",
      fontWeight: 900,
      lineHeight: 1.05,
      letterSpacing: "-0.04em",
      marginBottom: "1.5rem",
      maxWidth: 950,
      color: text,
    },
    heroSpan: { color: accent },
    heroSubtitle: {
      fontSize: "clamp(1rem, 1.8vw, 1.2rem)",
      color: muted,
      maxWidth: 580,
      lineHeight: 1.65,
      marginBottom: "3rem",
    },
    heroCtas: { display: "flex", gap: "1rem", flexWrap: "wrap" },
    primaryBtn: {
      background: accent,
      color: "#fff",
      border: "none",
      borderRadius: 8,
      padding: "16px 36px",
      fontSize: 14,
      fontWeight: 700,
      letterSpacing: "0.06em",
      cursor: "pointer",
      textTransform: "uppercase",
      transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    secondaryBtn: {
      background: "transparent",
      color: text,
      border: `1px solid ${border}`,
      borderRadius: 8,
      padding: "16px 36px",
      fontSize: 14,
      fontWeight: 600,
      letterSpacing: "0.06em",
      cursor: "pointer",
      textTransform: "uppercase",
      transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    section: {
      padding: "8rem clamp(1.5rem, 5vw, 4rem)",
      maxWidth: 1280,
      margin: "0 auto",
    },
    eyebrow: {
      fontSize: 12,
      letterSpacing: "0.22em",
      color: accent,
      textTransform: "uppercase",
      marginBottom: "0.85rem",
      fontWeight: 600,
    },
    sectionTitle: {
      fontSize: "clamp(2rem, 4vw, 3.5rem)",
      fontWeight: 800,
      letterSpacing: "-0.03em",
      lineHeight: 1.15,
      marginBottom: "1rem",
    },
    sectionDesc: {
      fontSize: 16,
      color: muted,
      lineHeight: 1.7,
      maxWidth: 540,
    },
    divider: {
      width: 64,
      height: 3,
      background: accent,
      margin: "1.5rem 0 2rem 0",
      borderRadius: 2,
    },
    statsBar: {
      background: accent,
      padding: "4rem clamp(1.5rem, 5vw, 4rem)",
    },
    statsGrid: {
      maxWidth: 1280,
      margin: "0 auto",
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
      gap: "2.5rem",
      textAlign: "center",
    },
    statNum: {
      fontSize: "clamp(2.2rem, 4vw, 3.5rem)",
      fontWeight: 900,
      color: "#fff",
      letterSpacing: "-0.03em",
    },
    statLabel: {
      fontSize: 12,
      letterSpacing: "0.14em",
      color: "rgba(255,255,255,0.8)",
      textTransform: "uppercase",
      marginTop: "0.5rem",
      fontWeight: 500,
    },
    servicesGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
      gap: "2rem",
      marginTop: "4rem",
    },
    serviceCard: {
      background: card,
      border: `1px solid ${border}`,
      borderRadius: 16,
      padding: "2.5rem",
      transition: "all 0.35s cubic-bezier(0.4, 0, 0.2, 1)",
      cursor: "default",
    },
    serviceIcon: {
      fontSize: 40,
      marginBottom: "1.5rem",
    },
    serviceTitle: {
      fontSize: 19,
      fontWeight: 700,
      marginBottom: "0.75rem",
      letterSpacing: "-0.02em",
    },
    serviceDesc: {
      fontSize: 14,
      color: muted,
      lineHeight: 1.7,
    },
    serviceTag: {
      display: "inline-block",
      marginTop: "1.5rem",
      fontSize: 12,
      letterSpacing: "0.08em",
      color: accent,
      textTransform: "uppercase",
      fontWeight: 600,
      transition: "gap 0.2s ease",
    },
    projectsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
      gap: "2rem",
      marginTop: "4rem",
    },
    projectCard: {
      background: card,
      border: `1px solid ${border}`,
      borderRadius: 16,
      overflow: "hidden",
      cursor: "pointer",
      transition: "all 0.35s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    projectImgPlaceholder: {
      height: 220,
      background: dark
        ? "linear-gradient(135deg, #1c1c1c 0%, #302412 100%)"
        : "linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 54,
      transition: "transform 0.5s ease",
    },
    projectBody: { padding: "1.5rem" },
    projectName: { fontSize: 19, fontWeight: 700, marginBottom: "0.35rem", letterSpacing: "-0.02em" },
    projectType: { fontSize: 13, color: muted, marginBottom: "1rem" },
    tagRow: { display: "flex", gap: "0.5rem", flexWrap: "wrap" },
    tag: {
      fontSize: 11,
      padding: "4px 12px",
      borderRadius: 20,
      background: accentLight,
      color: dark ? "#f59e0b" : "#b45309",
      fontWeight: 600,
      letterSpacing: "0.05em",
    },
    partnersSection: {
      borderTop: `1px solid ${border}`,
      borderBottom: `1px solid ${border}`,
      padding: "5rem clamp(1.5rem, 5vw, 4rem)",
      background: surface,
    },
    partnersInner: { maxWidth: 1280, margin: "0 auto" },
    partnersLabel: {
      textAlign: "center",
      fontSize: 12,
      letterSpacing: "0.22em",
      color: muted,
      textTransform: "uppercase",
      marginBottom: "3rem",
      fontWeight: 600,
    },
    partnersFlex: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "clamp(2rem, 6vw, 6rem)",
      flexWrap: "wrap",
    },
    partnerBadge: {
      display: "flex",
      alignItems: "center",
      gap: "1rem",
    },
    partnerAvatar: {
      width: 48,
      height: 48,
      borderRadius: 12,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 14,
      fontWeight: 800,
      color: "#fff",
    },
    partnerName: {
      fontSize: 16,
      fontWeight: 700,
      letterSpacing: "-0.01em",
    },
    testimonialWrap: {
      background: card,
      border: `1px solid ${border}`,
      borderRadius: 24,
      padding: "4rem clamp(1.5rem, 5vw, 5rem)",
      marginTop: "4rem",
      textAlign: "center",
      position: "relative",
      overflow: "hidden",
    },
    testimonialQuote: {
      fontSize: "clamp(1.1rem, 2.2vw, 1.5rem)",
      lineHeight: 1.65,
      fontWeight: 500,
      maxWidth: 750,
      margin: "0 auto 2.5rem",
      color: text,
    },
    testimonialAuthor: {
      fontSize: 16,
      fontWeight: 700,
    },
    testimonialRole: {
      fontSize: 13,
      color: accent,
      marginTop: "0.35rem",
      fontWeight: 500,
    },
    dotRow: {
      display: "flex",
      justifyContent: "center",
      gap: "0.6rem",
      marginTop: "2.5rem",
    },
    footer: {
      background: dark ? "#070707" : "#0f172a",
      color: "#94a3b8",
      padding: "6rem clamp(1.5rem, 5vw, 4rem) 3rem",
    },
    footerInner: {
      maxWidth: 1280,
      margin: "0 auto",
    },
    footerTop: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
      gap: "4rem",
      marginBottom: "4rem",
    },
    footerLogo: {
      fontSize: 26,
      fontWeight: 900,
      color: "#fff",
      letterSpacing: "-0.03em",
    },
    footerTagline: {
      fontSize: 14,
      lineHeight: 1.6,
      marginTop: "1rem",
      color: "#94a3b8",
    },
    footerHeading: {
      fontSize: 11,
      letterSpacing: "0.18em",
      textTransform: "uppercase",
      color: accent,
      marginBottom: "1.5rem",
      fontWeight: 700,
    },
    footerLink: {
      display: "block",
      fontSize: 14,
      color: "#cbd5e1",
      marginBottom: "0.75rem",
      cursor: "pointer",
      transition: "color 0.2s ease",
    },
    footerDivider: {
      borderTop: "1px solid rgba(255,255,255,0.1)",
      paddingTop: "2rem",
      display: "flex",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: "1.5rem",
      fontSize: 13,
      color: "#64748b",
    },
    mobileMenu: {
      position: "fixed",
      inset: 0,
      zIndex: 200,
      background: dark ? "rgba(13,13,13,0.98)" : "rgba(255,255,255,0.98)",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      gap: "2.5rem",
      backdropFilter: "blur(20px)",
      transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    mobileNavLink: {
      fontSize: "clamp(1.8rem, 6vw, 2.5rem)",
      fontWeight: 800,
      color: text,
      letterSpacing: "-0.03em",
      cursor: "pointer",
      transition: "transform 0.2s ease, color 0.2s ease",
    },
    closeBtn: {
      position: "absolute",
      top: 32,
      right: 32,
      background: "none",
      border: "none",
      fontSize: 28,
      color: text,
      cursor: "pointer",
    },
  };
